java_test(
    name = "worker_test",
    srcs = [
        "WorkerTest.java",
    ],
    test_class = "io.bazel.rules_scala.worker.WorkerTest",
    deps = [
        "//src/java/io/bazel/rules_scala/worker",
    ],
)
